# Generated by Django 4.2.4 on 2023-10-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='profile/default/default.jpg', upload_to='profile/profile_images'),
        ),
    ]
