# Generated by Django 4.2.4 on 2023-10-04 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_alter_productvariant_offer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_paid', models.PositiveIntegerField()),
                ('payment_mode', models.CharField(choices=[('Cash On Delivey', 'Cash On Delivery'), ('Pay With Razor Pay', 'Pay With Razor Pay')], max_length=50)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_was', models.PositiveIntegerField()),
                ('quantiy_was', models.PositiveSmallIntegerField(default=1)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered')], max_length=50)),
                ('order_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.orderaddress')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.payment')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.productvariant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
