# Generated by Django 4.2.4 on 2023-10-09 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_alter_productvariant_offer'),
        ('Orders', '0002_payment_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Orders.orderaddress'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Orders.payment'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Home.productvariant'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('RazorPay', 'RazorPay')], max_length=50),
        ),
    ]
