# Generated by Django 4.2.4 on 2023-10-13 02:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_alter_orders_order_address_alter_orders_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
