# Generated by Django 4.2.4 on 2023-10-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0009_alter_orders_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='akhil_6d808a9b-d291-4633-af04-85a81ac7c13d', editable=False),
        ),
    ]
