# Generated by Django 4.2.4 on 2023-10-15 11:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0013_alter_orders_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
