# Generated by Django 3.2.23 on 2023-12-28 15:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0018_alter_orders_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=150, unique=True),
        ),
    ]
