# Generated by Django 4.2.4 on 2023-09-18 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='product/images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='product/images')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='product/images')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='product/images')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='product/images')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='product/images')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='product/images')),
                ('color', models.ForeignKey(blank=True, default=1, help_text='if no color then leave it', null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.colors')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.product')),
            ],
        ),
    ]
