# Generated by Django 4.2.4 on 2023-09-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orginal_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
