# Generated by Django 4.2.4 on 2024-03-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_recentviewedproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentviewedproducts',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recentviewedproducts',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
