# Generated by Django 4.2.4 on 2023-09-18 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=250)),
                ('image_main', models.ImageField(upload_to='product/main/images')),
                ('available', models.BooleanField(default=True)),
                ('search_keywords', models.CharField(blank=True, help_text='Not required. Only for users to search for products on the website.', max_length=150, null=True)),
                ('brand', models.ForeignKey(blank=True, help_text='Not required.only if the brand has', null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.category')),
            ],
        ),
    ]
