# Generated by Django 4.2.4 on 2023-09-23 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_product_orginal_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='offer',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
