# Generated by Django 4.2.4 on 2023-09-23 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_productvariant_offer_alter_productvariant_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='offer',
            field=models.PositiveSmallIntegerField(blank=True, help_text='offer %', null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
