# Generated by Django 4.2.4 on 2024-03-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_productreviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
