# Generated by Django 4.2.4 on 2023-10-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_orders_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.UUIDField(default='akhil_<function uuid4 at 0x7f172a5ff760>', editable=False),
        ),
    ]
