# Generated by Django 4.2.4 on 2023-10-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0008_alter_orders_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='akhil_984c999b-2115-4abb-bccd-74d09f324a32', editable=False),
        ),
    ]
