# Generated by Django 4.2.4 on 2023-10-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0010_alter_orders_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='akhil_b83698dc-acb9-4f2b-98ba-7d632599b5a2', editable=False, unique=True),
        ),
    ]
