# Generated by Django 4.2.4 on 2023-10-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0011_alter_orders_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='akhil_d0bc6dea-292f-41ef-9601-a05248a57bbd', editable=False, unique=True),
        ),
    ]
